name: Download MicroPython Release Binaries

on:
  # Run manually from the Actions tab
  workflow_dispatch:

  # Run when this action changes
  push:
    paths:
      - '.github/workflows/download-mp-release.yaml'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  # Build job
  download:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Variables
        run: |
          INC_VER=$(cat _includes/mpVersion.txt)
          echo "VERSION=$INC_VER" >> $GITHUB_ENV
          INC_DATE=$(cat _includes/mpDate.txt)
          echo "DATE=$INC_DATE" >> $GITHUB_ENV
      - name: Remove Existing Release Binaries
        run: rm -r -f bin
      - name: Make Directory for New Release Binaries
        run: mkdir bin
      # Download generic firmware from MicroPython.Org site
      - name: Download Generic Boards
        run: |
          for BUILD in ESP32_GENERIC ESP32_GENERIC_S2 ESP32_GENERIC_S3-FLASH_4M ESP32_GENERIC_C3; do
            cd bin
            curl https://micropython.org/resources/firmware/$BUILD-$DATE-$VERSION.bin -O
            cd ..
          done
      # Download for Secific Boards
      - name: Download Specific Boards
        run: |
          for BUILD in M5STACK_ATOM UM_TINYS3 LOLIN_C3_MINI; do
            cd bin
            curl https://micropython.org/resources/firmware/$BUILD-$DATE-$VERSION.bin -O
            cd ..
          done
      # Commit downloaded release
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin
          # May be nothing to commit or push there were no net changes
          git commit -m "Downloaded MicroPython release $VERSION with release date $DATE" || true
          git push || true
