name: Download MicroPython Release Binaries

on:
  # Run manually from the Actions tab
  workflow_dispatch:

  # Run when this action changes
  push:
    paths:
      - '.github/workflows/download-mp-release.yaml'

env:
  VERSION: v1.23.0
  DATE: 20240602

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  # Build job
  download:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Remove Existing Release Binaries
        run: rm -r -f bin
      - name: Make Directory for New Release Binaries
        run: mkdir bin
      # Download generic firmware from MicroPython.Org site
      - name: Download ESP32 Generic Boards
        run: cd bin; curl https://micropython.org/resources/firmware/ESP32_GENERIC-$DATE-$VERSION.bin -O
      - name: Download ESP8266 Generic
        run: cd bin; curl https://micropython.org/resources/firmware/ESP8266_GENERIC-$DATE-$VERSION.bin -O
      - name: Download ESP32-S2 Generic
        run: cd bin; curl https://micropython.org/resources/firmware/ESP32_GENERIC_S2-$DATE-$VERSION.bin -O
      - name: Download ESP32-S3 Generic 4M Flash
        run: cd bin; curl https://micropython.org/resources/firmware/ESP32_GENERIC_S3-FLASH_4M-$DATE-$VERSION.bin -O
      - name: Download ESP32-C3 Generic
        run: cd bin; curl https://micropython.org/resources/firmware/ESP32_GENERIC_C3-$DATE-$VERSION.bin -O
      # Download for Secific Boards
      - name: Download Lolin S2 Pico
        run: cd bin; curl https://micropython.org/resources/firmware/LOLIN_S2_PICO-$DATE-$VERSION.bin -O
      - name: Download Feather S2 Neo
        run: cd bin; curl https://micropython.org/resources/firmware/UM_FEATHERS2NEO-$DATE-$VERSION.bin -O
      - name: Download M5 Stack Atom
        run: cd bin; curl https://micropython.org/resources/firmware/M5STACK_ATOM-$DATE-$VERSION.bin -O
      - name: Download Unexpected Maker TinyS3
        run: cd bin; curl https://micropython.org/resources/firmware/UM_TINYS3-$DATE-$VERSION.bin -O
      - name: Download Lolin C3 Mini
        run: cd bin; curl https://micropython.org/resources/firmware/LOLIN_C3_MINI-$DATE-$VERSION.bin -O
      # Commit downloaded release
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin
          # May be nothing to commit or push there were no net changes
          git commit -m "Downloaded MicroPython release $VERSION with release date $DATE" || true
          git push || true
